language: python
sudo: false
env:
  global:
    - OMP_NUM_THREADS=1
    - VECLIB_MAXIMUM_THREADS=1
    - EXTRAS=docs,matrix_scipy,matrix_mkl,export_mpl
    - PYTHON=python3
cache: pip
matrix:
  include:
    - name: "Python: 3.5"
      os: linux
      python: "3.5"
    - name: "Python: 3.6"
      os: linux
      python: "3.6"
    - name: "Python: 3.7"
      os: linux
      dist: xenial
      python: "3.7"
    - name: "Python: 3.6, Numpy: 1.12"
      os: linux
      python: "3.6"
      env:
        - EXTRAS=matrix_mkl,export_mpl
        - CONSTRAINTS=numpy==1.12
    - name: "Pypy"
      os: linux
      python: pypy3.5
      env:
        - EXTRAS=matrix_mkl,export_mpl
        - PYTHON=venv/bin/python3
      before_install:
        - wget --no-verbose -O - "$PYPY_URL" | tar xj
        - pypy*/bin/pypy3 -m venv venv
    - name: "Python"
      os: osx
      language: generic
      before_install:
        - wget --no-verbose -O python.pkg "$PYTHON_PKG_URL"
        - sudo installer -pkg python.pkg -target /
        - rm python.pkg
    - name: "Python: 3.x"
      os: windows
      language: shell
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
      env:
        - PYTHON=/c/Python/python.exe
install:
  - $PYTHON -m pip install --upgrade pip wheel
  - touch .constraints
  - for CONSTRAINT in $CONSTRAINTS; do echo $CONSTRAINT >> .constraints; done
  - $PYTHON -m pip install --upgrade --constraint .constraints numpy
  - $PYTHON -m pip install --upgrade --constraint .constraints .[$EXTRAS] coverage codecov
script:
  - $PYTHON -m coverage run -m unittest -b
after_success:
  - $PYTHON -m coverage xml -i
  - $PYTHON -m codecov --file coverage.xml
# vim: ts=2:sts=2:sw=2:et
