language: python
sudo: false
env:
  global:
    - OMP_NUM_THREADS=1
    - VECLIB_MAXIMUM_THREADS=1
    - EXTRAS=docs,matrix_scipy,matrix_mkl,export_mpl
    - PYTHON=python3
    - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
cache: pip
matrix:
  include:
    - name: "Python: 3.5"
      os: linux
      python: "3.5"
    - name: "Python: 3.6"
      os: linux
      python: "3.6"
    - name: "Python: 3.7"
      os: linux
      dist: xenial
      python: "3.7"
    - name: "Python: 3.6, Numpy: 1.12"
      os: linux
      python: "3.6"
      env:
        - EXTRAS=matrix_mkl,export_mpl
        - LOCAL_CONSTRAINTS=numpy==1.12
    - name: "Python"
      os: osx
      language: generic
      before_install:
        - wget --no-verbose -O python.pkg "$PYTHON_PKG_URL"
        - sudo installer -pkg python.pkg -target /
        - rm python.pkg
    - name: "Python: 3.x"
      os: windows
      language: shell
      before_install:
        - choco install python3 --version=$PYTHON_VERSION_WINDOWS --params "/InstallDir:C:\\Python"
      env:
        - PYTHON=/c/Python/python.exe
install:
  - $PYTHON -m pip install --upgrade pip wheel
  - touch .constraints
  - for CONSTRAINT in $LOCAL_CONSTRAINTS $CONSTRAINTS; do echo $CONSTRAINT >> .constraints; done
  - $PYTHON -m pip install --upgrade --constraint .constraints numpy
  - $PYTHON -m pip install --upgrade --constraint .constraints .[$EXTRAS] coverage coveralls
script:
  - $PYTHON -m coverage run -m unittest -b
after_success:
  - $PYTHON -m coveralls
# vim: ts=2:sts=2:sw=2:et
